TRAIN_DATA="./data/VisionThink-Smart-Train"
VAL_DATA="./data/VisionThink-Smart-Val" 
EXP_NAME=AdaptVision_train

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=dtpo \
    data.prompt_type="image_crop_agent" \
    data.system_prompt="image_crop_agent" \
    data.train_file=${TRAIN_DATA} \
    data.val_files=${VAL_DATA} \
    data.train_batch_size=512 \
    data.max_prompt_length=8192 \
    data.max_response_length=8192 \
    data.image_key=images \
    data.mask_blank=False \
    data.acc_reward_weight=1.0 \
    data.format_reward_weight=0.5 \
    data.area_penalty_weight=0.2 \
    data.adaptive_area=True \
    data.acc_condition=False \
    data.bbox_reward_weight=0.1 \
    data.balance_reward_weight=0 \
    data.min_area_ratio=0.0 \
    data.tool_call_penalty=0.1 \
    data.direct_answer_penalty=0.1\
    data.lambda_coeff=0.3\
    data.general_qa_reward_fn="general_qa_bbox" \
    data.val_general_qa_reward_fn="general_qa_bbox" \
    data.gpt_extract_answer=True \
    data.extract_answer_tags="split" \
    data.return_raw_chat=True \
    data.gpt_threads=100 \
    data.tool_call=True \
    data.use_tgt_size=True \
    reward_model.reward_manager=naive_multithreads_bbox \
    reward_model.log_rewards_separately=True \
    reward_model.enable=False \
    actor_rollout_ref.model.path=Qwen/Qwen2.5-VL-7B-Instruct \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.control_level=tool_level\
    actor_rollout_ref.actor.control_alpha=0.5\
    actor_rollout_ref.actor.clip_ratio_high=0.24 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=32 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0.001 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.actor.use_multi_turn_response_mask=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.max_num_batched_tokens=32768 \
    actor_rollout_ref.rollout.name=vllm_multi_turn_crop_call \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.rollout.n=16 \
    actor_rollout_ref.rollout.max_generation_round=2 \
    'actor_rollout_ref.rollout.limit_mm_per_prompt={'image': 2}' \
    actor_rollout_ref.rollout.use_raw_image=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0 \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name='AdaptVision' \
    trainer.experiment_name=${EXP_NAME}\
    trainer.val_generations_to_log_to_wandb=128 \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=5 \
    trainer.default_local_dir=./trials/${EXP_NAME}\
    trainer.test_freq=5 \
    trainer.total_epochs=10 \
    trainer.log_training_rollouts_freq=5 \
    trainer.train_generations_to_log_to_wandb=256 \
    trainer.use_3drope=True \
    trainer.soft_tool_call_penalty_ratio=0.2 \
    reward_model.log_rewards_separately=True \
    trainer.rejection_sample=True \
    trainer.rejection_sample_multiplier=1 \
